config/routes.rb
Rails.application.routes.draw do
  resources :forecasts
  root      "forecasts#index"

end

app/models/forecast.rb
class Forecast < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  before_action :set_forecast, only: [:show, :edit, :update, :destroy]

  # GET /forecasts
  # GET /forecasts.json
  def index
    @forecasts = Forecast.last(10)
    @forecast = Forecast.new

=begin    @response = RestClient.get 'api.openweathermap.org/data/2.5/weather', 
                {:params => {'zip' => :zip, 
                             'countrycode' => 'us',
                             'units' => 'imperial', 
                             'APPID' => 'be6738da9d03b99569232206aebfcde2'}}

    @parsed = JSON.parse(@response)



    @forecast.current_temp = @parsed["main"]["temp"]
    @forecast.high_low = @parsed["main"]["temp_max"]  
    @forecast.wind = @parsed["wind"]["speed"] 
    @forecast.last_checked = DateTime.now
    #@forecast.save
=end  
  end

  # GET /forecasts/1
  # GET /forecasts/1.json
  def show
  end

  # GET /forecasts/new
  def new
    @forecast = Forecast.new
  end

  # GET /forecasts/1/edit
  def edit
  end

  # POST /forecasts
  # POST /forecasts.json
  def create

     @response = RestClient.get 'api.openweathermap.org/data/2.5/weather', 
                {:params => {'zip' => forecast_params[:zip], 
                             'countrycode' => 'us',
                             'units' => 'imperial', 
                             'APPID' => 'be6738da9d03b99569232206aebfcde2'}}

@parsed = JSON.parse(@response)


    @forecast = Forecast.new(forecast_params)
    @forecast.current_temp = @parsed["main"]["temp"]
    @forecast.high_low = @parsed["main"]["temp_max"]  
    @forecast.wind = @parsed["wind"]["speed"] 
    @forecast.last_checked = DateTime.now
    
    respond_to do |format|
      if @forecast.save
        format.html { redirect_to @forecast, notice: 'Forecast was successfully created.' }
        format.json { render :show, status: :created, location: @forecast }
      else
        format.html { render :new }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forecasts/1
  # PATCH/PUT /forecasts/1.json
  def update
    respond_to do |format|
      if @forecast.update(forecast_params)
        format.html { redirect_to @forecast, notice: 'Forecast was successfully updated.' }
        format.json { render :show, status: :ok, location: @forecast }
      else
        format.html { render :edit }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forecasts/1
  # DELETE /forecasts/1.json
  def destroy
    @forecast.destroy
    respond_to do |format|
      format.html { redirect_to forecasts_url, notice: 'Forecast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forecast
      @forecast = Forecast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forecast_params
      params.require(:forecast).permit(:zip, :current_temp, :high_low, :wind, :last_checked)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/views/forecasts/_form.html.erb
<%= form_for(@forecast) do |f| %>
  <% if @forecast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forecast.errors.count, "error") %> prohibited this forecast from being saved:</h2>

      <ul>
      <% @forecast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Please enter a zipcode" %><br>
    <%= f.text_field :zip %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forecasts/edit.html.erb
<h1>Editing Forecast</h1>

<%= render 'form' %>

<%= link_to 'Show', @forecast %> |
<%= link_to 'Back', forecasts_path %>

app/views/forecasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forecasts</h1>
<table>
  <thead>
    <tr>
      <th>Zip</th>
      <th>Current temp</th>
      <th>High low</th>
      <th>Wind</th>
      <th>Last checked</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forecasts.each do |forecast| %>
      <tr>
        <td><%= forecast.zip %></td>
        <td><%= forecast.current_temp %></td>
        <td><%= forecast.high_low %></td>
        <td><%= forecast.wind %></td>
        <td><%= forecast.last_checked %></td>
        <td><%= link_to 'Show', forecast %></td>
        <td><%= link_to 'Edit', edit_forecast_path(forecast) %></td>
        <td><%= link_to 'Destroy', forecast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= render 'form' %>

app/views/forecasts/new.html.erb
<h1>New Forecast</h1>

<%= render 'form' %>

<%= link_to 'Back', forecasts_path %>

app/views/forecasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zip:</strong>
  <%= @forecast.zip %>
</p>

<p>
  <strong>Current temp:</strong>
  <%= @forecast.current_temp %>
</p>

<p>
  <strong>High low:</strong>
  <%= @forecast.high_low %>
</p>

<p>
  <strong>Wind:</strong>
  <%= @forecast.wind %>
</p>

<p>
  <strong>Last checked:</strong>
  <%= @forecast.last_checked %>
</p>

<%= link_to 'Edit', edit_forecast_path(@forecast) %> |
<%= link_to 'Back', forecasts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab11</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>